CREATE TABLE "KPI_PREDICTION" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"TIMESTAMP" VARCHAR2(30) COLLATE "USING_NLS_COMP",
	"DD_MM_YY" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"UPPER_PREDICTION" NUMBER(10,3),
	"LOWER_PREDICTION" NUMBER(10,3),
	"PREDICTED_VALUE" NUMBER(10,3),
	"ACTUAL_VALUE" NUMBER(10,3),
	"EXCEEDS_THRESHOLD" NUMBER(3,1),
	"UNDER_THRESHOLD" NUMBER(3,1),
	"FLAG_CELL" NUMBER(3,1),
	"DELTA_FROM_PREDICTION" NUMBER(10,3),
	"DELTA_FROM_BOUND" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "KPI_DEGRADATION_DAILY" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"DATE" VARCHAR2(30) COLLATE "USING_NLS_COMP",
	"DL_USER_THROUGHPUT_MBPS_AVERAGE" NUMBER(10,3),
	"DL_USER_THROUGHPUT_MBPS_PCT_CHANGE" NUMBER(10,3),
	"DEGRADED" NUMBER(10,3),
	"FLAG" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "KPI_DEGRADATION_DAILY_SUMMARY" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"DL_USER_THROUGHPUT_MBPS_AVERAGE" NUMBER(10,3),
	"DL_USER_THROUGHPUT_MBPS_PCT_CHANGE" NUMBER(10,3),
	"FLAG" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";


CREATE TABLE "FORECAST_DATA" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"TIMESTAMP" VARCHAR2(30) COLLATE "USING_NLS_COMP",
	"UPPER_PREDICTION" NUMBER(10,3),
	"LOWER_PREDICTION" NUMBER(10,3),
	"PREDICTED" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "KPI_ANOMALY" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"START_TIME" VARCHAR2(30) COLLATE "USING_NLS_COMP",
	"DATE" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"MAINTENANCE_WINDOW" VARCHAR2(5) COLLATE "USING_NLS_COMP",
	"HISTORICAL_UPPER_BOUND" NUMBER(10,3),
	"HISTORICAL_LOWER_BOUND" NUMBER(10,3),
	"EXCEEDS_THRESHOLD" NUMBER(10,3),
	"UNDER_THRESHOLD" NUMBER(10,3),
	"OUT_OF_RANGE" NUMBER(10,1),
	"PCT_DELTA_FROM_HIST_PREDICTION" NUMBER(10,1),
	"PCT_DELTA_FROM_HIST_BOUND" NUMBER(10,1),
	"AI_PREDICTION" NUMBER(10,3),
	"ACTUAL_VALUE" NUMBER(10,3),
	"HISTORICAL_PREDICTION" NUMBER(10,3),
	"DELTA_FROM_AI_PREDICTION" NUMBER(10,3),
	"DELTA_FROM_HIST_PREDICTION" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "KPI_DEGRADATION_WEEKLY_SUMMARY" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"DL_USER_THROUGHPUT_MBPS_AVERAGE" NUMBER(10,3),
	"DL_USER_THROUGHPUT_MBPS_PCT_CHANGE" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";

CREATE TABLE "KPI_DEGRADATION_WEEKLY" (
    "CELL_NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP",
    "YEAR_WEEK" VARCHAR2(20) COLLATE "USING_NLS_COMP",
    "START_DATE" VARCHAR2(20) COLLATE "USING_NLS_COMP",
	"DL_USER_THROUGHPUT_MBPS_AVERAGE" NUMBER(10,3),
	"DL_USER_THROUGHPUT_MBPS_PCT_CHANGE" NUMBER(10,3),
	"DEGRADED" NUMBER(10,3),
	"FLAG" NUMBER(10,3)
) DEFAULT COLLATION "USING_NLS_COMP";