SELECT * FROM AI_ADMIN.KPI_PREDICTION WHERE rownum <= 100000;

DELETE FROM AI_ADMIN.FORECAST_DATA;

DELETE FROM AI_ADMIN.KPI_ANOMALY;

DELETE FROM AI_ADMIN.KPI_DEGRADATION_DAILY;
DELETE FROM AI_ADMIN.KPI_DEGRADATION_DAILY_SUMMARY;

DELETE FROM AI_ADMIN.KPI_DEGRADATION_WEEKLY_SUMMARY;
DELETE FROM AI_ADMIN.KPI_DEGRADATION_WEEKLY;

DELETE FROM AI_ADMIN.KPI_DEGRADATION_DAILY;
DELETE FROM AI_ADMIN.KPI_DEGRADATION_DAILY_SUMMARY;

DROP TABLE AI_ADMIN.KPI_DEGRADATION_DAILY_SUMMARY;
DROP TABLE AI_ADMIN.KPI_ANOMALY;